name: MacOS
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  macosx:
    runs-on: macos-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        static_deps: ["static", ""]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build dependencies
        run: |
          pip install --upgrade pip setuptools wheel build
          brew install libxml2 libxmlsec1 pkg-config
      - name: Build macosx wheel
        env:
          CC: clang
          PYXMLSEC_STATIC_DEPS: ${{ matrix.static_deps }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix)/opt/libxml2/lib/pkgconfig"
          python -m build
          rm -rf build/
      - name: Install test dependencies
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix)/opt/libxml2/lib/pkgconfig"
          pip install --upgrade --no-binary=lxml -r requirements-test.txt
          pip install xmlsec --only-binary=xmlsec --no-index --find-links=dist/
      - name: Run tests
        run: |
          pytest -v --color=yes
